[plugin]
repository = "https://github.com/Berna-L/ffxiv-tf2-hud-plugin.git"
commit = "3b5b0c64f6963e9c999502f56fc8d9c6fc13eee1"
owners = ["Berna-L"]
project_path = "Tf2Hud"
changelog = """
[General]
Add failsafe if Dalamud thinks a Windows user is under Linux.

(Thanks to AlexFlipnote for the report!)
"""
